### ISSUE TITLE
Arithmetic Operations Errors in arithmetic_operations.erl

### ISSUE THREAD

**Issue by Xeazhar** [palangdan-joanalyn/9365_Team01_Erlang_Project-SourceCode#16]
> [!NOTE]
>  **When running rebar3 eunit to verify dependencies and compile the project, the following issues occur in the src/arithmetic_operations.erl file:**

**Error**
1. Undefined Function

- `function multiply_two_num/0 undefined` This error indicates that the function `multiply_two_num/0` is referenced but has not been defined in the module.

**Warnings**
1. Unused Function

- function `multiply_two_num/2` is unused The `multiply_two_num/2` function is defined but is not called anywhere in the module, resulting in a warning.

2. Unused Variables

- `variable 'Num1' is unused` This warning appears twice, on lines 15 and 19, and indicates that the variable Num1 is declared but not used within its scope.

> [!IMPORTANT]
>  **Expected Behavior** The code should compile without errors or warnings. All defined functions and variables should be either used or removed if unnecessary.

> [!WARNING]
>  **Actual Behavior** Compilation halts due to the undefined function error. Warnings about unused functions and variables are displayed, indicating potential redundancies or incomplete logic.

After implementing the changes, run rebar3 eunit again to verify successful compilation and resolve all errors and warnings.

**Comment by RuzzLee** [comment]
Debugged the program to resolve both errors and warnings
